import random

def generate_quote():
    quotes = [
        "The only way to do great work is to love what you do. - Steve Jobs",
        "Innovation distinguishes between a leader and a follower. - Steve Jobs",
        "Stay hungry, stay foolish. - Steve Jobs",
        "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
        "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston S. Churchill",
        "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
        "Believe you can and you're halfway there. - Theodore Roosevelt",
        "The best way to predict the future is to invent it. - Alan Kay",
        "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
        "The mind is everything. What you think you become. - Buddha",
        "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
        "The purpose of our lives is to be happy. - Dalai Lama",
        "The only true wisdom is in knowing you know nothing. - Socrates",
        "Life is what happens when you're busy making other plans. - John Lennon",
        "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
        "It does not matter how slowly you go as long as you do not stop. - Confucius",
        "The journey of a thousand miles begins with one step. - Lao Tzu",
        "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
        "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
        "You miss 100% of the shots you don't take. - Wayne Gretzky",
        "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
        "A person who never made a mistake never tried anything new. - Albert Einstein",
        "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein",
        "Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world, stimulating progress, giving birth to evolution. - Albert Einstein",
        "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
        "The only way to do great work is to love what you do. - Steve Jobs",
        "Innovation distinguishes between a leader and a follower. - Steve Jobs",
        "Stay hungry, stay foolish. - Steve Jobs",
        "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
        "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston S. Churchill",
        "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
        "Believe you can and you're halfway there. - Theodore Roosevelt",
        "The best way to predict the future is to invent it. - Alan Kay",
        "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
        "The mind is everything. What you think you become. - Buddha",
        "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
        "The purpose of our lives is to be happy. - Dalai Lama",
        "The only true wisdom is in knowing you know nothing. - Socrates",
        "Life is what happens when you're busy making other plans. - John Lennon",
        "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
        "It does not matter how slowly you go as long as you do not stop. - Confucius",
        "The journey of a thousand miles begins with one step. - Lao Tzu",
        "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
        "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
        "You miss 100% of the shots you don't take. - Wayne Gretzky",
        "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
        "A person who never made a mistake never tried anything new. - Albert Einstein",
        "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein",
        "Imagination is more important than knowledge. For knowledge is limited, whereas imagination embraces the entire world, stimulating progress, giving birth to evolution. - Albert Einstein",
        "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    ]
    return random.choice(quotes)

if __name__ == "__main__":
    print(generate_quote())
